---
- name: Cisco RBB configuration
  hosts: rbb  # Asegúrate de que "rbb" esté correctamente definido en tu archivo de inventario
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_network_cli_ssh_type: paramiko

  tasks:
  - name: Shutdown unusable interfaces
    cisco.ios.ios_interfaces:
      config:
        - name: GigabitEthernet0/0
          description: Unused interface
          enabled: false
        - name: GigabitEthernet0/3
          description: Unused interface
          enabled: false
        - name: GigabitEthernet0/4
          description: Unused interface
          enabled: false
        - name: GigabitEthernet0/5
          description: Unused interface
          enabled: false
        - name: GigabitEthernet0/6
          description: Unused interface
          enabled: false
        - name: GigabitEthernet0/7
          description: Unused interface
          enabled: false
        - name: GigabitEthernet0/8
          description: Unused interface
          enabled: false
        - name: GigabitEthernet0/9
          description: Unused interface
          enabled: false

  - name: Configure Interface GigabitEthernet0/2
    cisco.ios.ios_config:
      lines:
        - description To ASA connection
        - ip address 30.0.0.2 255.0.0.0
        - no shutdown
      parents: interface gigabitEthernet0/2

  - name: Configure Route to Inside
    cisco.ios.ios_config:
      lines:
        - ip route 10.0.0.0 255.0.0.0 30.0.0.1
