---
- name: Configurar RBB
  hosts: rbb
  tasks:
    - name: Configurar interfaz y OSPF en RBB
      cisco.ios.ios_config:
        lines:
          - "hostname RBB"
          - "interface fa0/0"
          - "ip address 30.0.0.2 255.0.0.0"
          - "no shutdown"
          - "exit"
          - "router ospf 1"
          - "network 30.0.0.0 255.0.0.0 area 0"
          - "ip route 0.0.0.0 0.0.0.0 30.0.0.1"
          - "line vty 0 4"
          - "password cisco"
          - "login"
          - "transport input telnet"
          - "exit"
          - "exit"

    - name: Guardar configuración
      cisco.ios.ios_command:
        commands:
          - "write memory"
